module.exports = [
    {
      name: 'Tom Brady',
      position: 'QB',
      tag: 'Offense',
      ovr: 100,
      img: 'https://www.kbksports.com/wp-content/uploads/02435D74-1E35-4527-8F85-8716E865766C.jpeg',
    },
    {
      name: 'Aaron Donald',
      position: 'DT',
      tag: 'Defense',
      ovr: 100,
      img: 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/61HuAznRZBL.jpg',
    },
    {
      name: 'Charles Woodson',
      position: 'CB',
      tag: 'Defense',
      ovr: 99,
      img: 'https://i.ebayimg.com/images/g/41MAAOSw5e5i2OxX/s-l1600.jpg',
    },
    {
      name: 'Quenton Nelson',
      position: 'RG',
      tag: 'Offense',
      ovr: 98,
      img: 'https://m.media-amazon.com/images/I/61a32MOKgFL.jpg',
    },
    {
      name: 'Lane Johnson',
      position: 'RT',
      tag: 'Offense',
      ovr: 98,
      img: 'https://i.ebayimg.com/images/g/1F8AAOSwRkNgHGuo/s-l1600.jpg',
    },
    {
      name: 'Trent Williams',
      position: 'LT',
      tag: 'Offense',
      ovr: 98,
      img: 'https://m.media-amazon.com/images/I/61P3MMtxN8L.jpg',
    },
    {
      name: 'Jason Kelce',
      position: 'C',
      tag: 'Offense',
      ovr: 99,
      img: 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51hb2FGN68S._UF1000,1000_QL80_.jpg',
    },
    {
      name: 'Christian McCaffrey',
      position: 'RB',
      tag: 'Offense',
      ovr: 99,
      img: 'https://assets.paniniamerica.net/catalog/product/pack/315/036A_68183_0004F1_BC2202Bas_BC_8_172_310.png',
    },
    {
      name: 'Larry Allen',
      position: 'LG',
      tag: 'Offense',
      ovr: 100,
      img: 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/71WF5D47wUL.jpg',
    },
    {
      name: 'Deebo Samuel',
      position: 'WR',
      tag: 'Offense',
      ovr: 98,
      img: 'https://assets.paniniamerica.net/catalog/product/pack/580/053A_70327_0008F1_BC2202Bas_BC_2_190_478.png',
    },
    {
      name: 'Julio Jones',
      position: 'WR',
      tag: 'Offense',
      ovr: 99,
      img: 'https://assets.paniniamerica.net/catalog/product/pack/580/321A_70328_0008F2_BC2202Bas_BC_6_56_199.png',
    },
    {
      name: 'Vince Wilfork',
      position: 'DT',
      tag: 'Defense',
      ovr: 98,
      img: 'https://m.media-amazon.com/images/I/51PyurX9GJL._UF1000,1000_QL80_.jpg',
    },
    {
      name: 'JJ Watt',
      position: 'DE',
      tag: 'Defense',
      ovr: 100,
      img: 'https://assets.paniniamerica.net/catalog/product/pack/692/180A_76736_0012F2_BC2202Bas_BC_1_815_999.png',
    },
    {
      name: 'Joey Bosa',
      position: 'DE',
      tag: 'Defense',
      ovr: 98,
      img: 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/713edi3THkL.jpg',
    },
    {
      name: 'Ray Lewis',
      position: 'MLB',
      tag: 'Defense',
      ovr: 100,
      img: 'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/71jvcILSUeL.jpg',
    },
    {
      name: 'Luke Kuechly',
      position: 'OLB',
      tag: 'Defense',
      ovr: 100,
      img: 'https://m.media-amazon.com/images/I/61VEpH2JW9L.jpg',
    },
    {
      name: 'Von Miller',
      position: 'OLB',
      tag: 'Defense',
      ovr: 98,
      img: 'https://assets.paniniamerica.net/catalog/product/pack/580/204A_70328_0008F2_BC2202Bas_BC_1_1001_3250.png',
    },
    {
      name: 'Kam Chancellor',
      position: 'SS',
      tag: 'Defense',
      ovr: 99,
      img: 'https://m.media-amazon.com/images/I/61onASKdQzL._UF1000,1000_QL80_.jpg',
    },
    {
      name: 'Earl Thomas',
      position: 'FS',
      tag: 'Defense',
      ovr: 98,
      img: 'https://m.media-amazon.com/images/I/71tURWh0EfL.jpg',
    },
    {
      name: 'Richard Sherman',
      position: 'CB',
      tag: 'Defense',
      ovr: 99,
      img: 'https://m.media-amazon.com/images/I/61PDZFi9HyL.jpg',
    }
  ]